Global:
  App: GoIrisFrontend # 项目名称
  Env: Dev # 开发环境
GoIrisFrontend: # 项目名称
  Dev: # 开发环境
    MySql: #M ySQL数据库配置
      Frontend: # 数据库配置名称
        Host: 127.0.0.1
        User: root
        DbName: iris_test
        Pwd:
        Port: 3306
    Log: # Log日志配置
      Service:
        TimeFormat: 2006/01/02 15:04:05.000 -0700
        Level: info # 不写默认是info
        Extra:
        Formatter: json
        StorageMode:
          File:
            Formatter: json
            Rotation:
              Hours: 24
              Count: 7
              Postfix: .%Y%m%d%H%M
            Path:
              Panic: panic
              Fatal: fatal
              Error: error
              Warn:  warn
              Debug: debug
              Trace: trace
              Info:  info
      Recovery:
        TimeFormat: 2006/01/02 15:04:05.000 -0700
        Level: info # 不写默认是info
        Extra:
        Formatter: json
        StorageMode:
          File:
            Formatter: json
            Rotation:
              Hours: 24
              Count: 7
              Postfix: .%Y%m%d%H%M
            Path:
              Panic: panic
              Fatal: fatal
              Error: error
              Warn:  warn
              Debug: debug
              Trace: trace
              Info:  info
    Validator:
      Lang:
        Zh:
          Locale: zh
          Label: label
        En:
          Locale: en
          Label: label
